export default {
	'cn':{
		'WIDTH_TEST':'这里一共包含十六个普通的中文字符',
		'HELLO':'你好',
		'THANKS':'谢谢',
		'HOME':'首页',
		'MYLAB':'实验室',
		'DICE':'骰子布局',
		'TRANSLATOR':'多国语',
		'MYMAP':'地图插件',
		'MYGESTURE':'手势识别',
		'GA':'遗传算法',
		'CIRCULAR':'环形进度条',
		'PERMISSION':'权限控制'
	},
	'en':{
		'WIDTH_TEST':'Here are sixteen common Chinese characters',
		'HELLO':'Hello',
		'THANKS':'Thanks',
		'HOME':'Home',
		'MYLAB':'Lab',
		'DICE':'Flex-Dice',
		'TRANSLATOR':'Translator',
		'MYMAP':'Vue-Map',
		'MYGESTURE':'Gesture',
		'GA':'Genetic Algorithm',
		'CIRCULAR':'Circular',
		'PERMISSION':'Permission'
	},
	'fr':{
		'WIDTH_TEST':'Il contient un total de 16 caractères chinois ordinaire',
		'HELLO':'Bonjour',
		'THANKS':'Merci.',
		'HOME':'d\'accueil',
		'MYLAB':'Lab',
		'DICE':'Les dés',
		'TRANSLATOR':'Traduction',
		'MYMAP':'En ligne',
		'MYGESTURE':'Geste',
		'GA':'GA',
		'CIRCULAR':'Circular'
	},
	'de':{
		'WIDTH_TEST':'Hier umfasst 16 normale chinesische Zeichen',
		'HELLO':'Hallo',
		'THANKS':'Danke.',
		'HOME':'Home',
		'MYLAB':'Labor',
		'DICE':'Würfel - layout',
		'TRANSLATOR':'übersetzung',
		'MYMAP':'Karte',
		'MYGESTURE':'Gesten',
		'GA':'GA',
		'CIRCULAR':'Circular'
	},
}